### ISSUE TITLE
Question: How to rename the server?

### ISSUE THREAD

**Issue by megaroeny** [ph1p/figma-chat-server#1]
Hi, I was trying to rename the server chat for a specific file to just "Patterns". When I did that, I think I broke something. Is this not the intended behavior?

### Attempted to rename:
![image](https://user-images.githubusercontent.com/1559447/63967863-4d14d380-ca6c-11e9-97f5-3089762a318c.png)

### Resulted in:
![image](https://user-images.githubusercontent.com/1559447/63967874-530ab480-ca6c-11e9-8fe2-6f4c38494143.png)

Then I also tried adding a suffix after the default server URL, and now my window is constantly trying to connect. Reinstalling the app, restarting Figma doesn't work. My browser session works fine though. Is there a way I can completely start over on the **desktop** app?

![image](https://user-images.githubusercontent.com/1559447/63968655-31aac800-ca6e-11e9-9011-2891041c2bd7.png)

**Comment by ph1p** [comment]
Hi @jaminroe! This is the chat server (: (default: https://figma-chat.ph1p.dev) 

You cannot set the name of the server.

**Comment by megaroeny** [comment]
Oh wow, okay! I understand now. Any idea how I can completely uninstall the plugin (besides just in Figma's app) so that I can start over? I assume there are some local files it installs somewhere on the Mac? If not, any ideas on how how to fix my issue? It's just stuck on "Connecting..." no matter what I do or even reinstall.

**Comment by ph1p** [comment]
Simply click on the settings button and paste the default URL(https://figma-chat.ph1p.dev) inside the input field. I will extend the settings and rethink about the labels.

**Comment by ph1p** [comment]
Ok. I've read your comment again. Sorry, I think this is a bug. I take a look at it and fix it as fast as I can!

**Comment by ph1p** [comment]
@jaminroe I've published a fixed version

**Comment by megaroeny** [comment]
Great! I can now adjust my settings even though there's a connection issue.
