### ISSUE TITLE
Color contrast for chat colors

### ISSUE THREAD

**Issue by megaroeny** [ph1p/figma-chat-server#2]
Some colors make the text barely legible. I would check the combinations and swap the text with white for some. See below:

![image](https://user-images.githubusercontent.com/1559447/63968476-ceb93100-ca6d-11e9-85af-2fbb2958ca0b.png)

**Comment by ph1p** [comment]
You're right! I will check and update it ;)

**Comment by megaroeny** [comment]
Awesome, thanks!

**Comment by ph1p** [comment]
Updated it in the latest version. Just open Figma Chat.
